export const ADD_TASK = "ADD_TASK";
export const REMOVE_TASK = "REMOVE_TASK";
export const COMPLETE_TASK = "COMPLETE_TASK";
export const ON_TOGGLE_IMPORTANT_TASK = "ON_TOGGLE_IMPORTANT_TASK";

export const CHANGE_FILTER = "CHANGE_FILTER";
